### ISSUE TITLE
Freeze in middle of job when a block found with proxy-ltc

### ISSUE THREAD

**Issue by BlackTurtle123** [jansenmarc/WavesGatewayLTCExample#3]
Sometimes the framework seems to freeze when it founds a tx with some proxy-ltc inside it.
It doesn't throw errors, it just freezes. Doing nothing.
Only on block with "fake" ltc inside. Other blocks it goes as fast as light for scanning.
Other times it doesn't freeze.
Any reason for this?

**Comment by henning96** [comment]
I have no idea.

**Comment by BlackTurtle123** [comment]
Used another RPC proxy, the bahving didnt't happen again.
For now it can be closed.
