### ISSUE TITLE
[Question] Why is max parallel connections 1?

### ISSUE THREAD

**Issue by BlackTurtle123** [jansenmarc/WavesGatewayLTCExample#4]
Why is max parallel connections 1? 
And not higher?

https://github.com/jansenmarc/WavesGatewayLTCExample/blob/14aaf9de5740ce32d175efa413f0060561421c93/waves_litecoin_gateway/litecoin_gateway.py#L38

When it's at 1 the gateway becomes stuck on validating addr from time to time. But there is most likely a reason why this 1 is set?

**Comment by henning96** [comment]
I don't know why, but it caused issues in local testing when there are multiple parallel connections to the litecoin node.

**Comment by BlackTurtle123** [comment]
Have you tryed other bitcoinrpc's or why did you pick this one?
I notice it gives issues to have multiple connections sometimes, but having one makes everything go block when tx happens and the thread is used.

**Comment by BlackTurtle123** [comment]
This can be closed since this q isn't needed when using another RPC.
The used RPC is very old, and therefore advised to upgrade to for example slickrpc.
