### ISSUE TITLE
One of the modules isn't installing

### ISSUE THREAD

**Issue by CryptoLover705** [jansenmarc/WavesGatewayLTCExample#5]
` pip3 install -r requirements.txt 
Requirement already satisfied: python-bitcoinrpc>=1.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1))
Collecting waves-gateway>=1.0.0 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7e/cf/1c075985425ff3ca93e60d00f91abf3b79d7c9ad2363630d2ac8426a9bb7/waves_gateway-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jgpq5rxn/waves-gateway/`

**Comment by jansenmarc** [comment]
Please make sure you have setuptools installed.

**Comment by CryptoLover705** [comment]
Ahh yeah ok, Sorry  I didn't notice that lol it was early AM when I tried it
