### ISSUE TITLE
problem with application config

### ISSUE THREAD

**Issue by alexeydad1** [jansenmarc/WavesGatewayLTCExample#6]
Hi, I'm having trouble getting the project started. Please tell us more about these config settings

[gateway_address]
owner = what parameter write here, nowhere not was able find that such "OWNER"?
waves_public_key = Why is this variable not a public key but a wallet Address?
coin_public_key = Here, too, to enter wallet address?

In advance thank you for help

**Comment by PyWaves** [comment]
owner needs to be the gateway address in the blockchain you want to connect. Same for coin_publicKey. waves_public_key is the same as the address for a nasty workaround.
